# application.yml
server:
  port: 18088

spring:
  application:
    name: huawei-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver

#    1.0 本地mysql数据库 (简称: 01环境)
    url: jdbc:mysql://127.0.0.1:3306/ocpmgp_project2?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 110308


    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

  #springboot 和springcloud版本冲突，暂时解决办法
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

#模块标识
module-id: 5

# mybatis
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  type-aliases-package: com.ecdata.cmp.huawei.entity
  global-config:
    #刷新mapper 该配置不建议在生产环境打开
    refresh: true
    db-config:
      #主键类型com.baomidou.mybatisplus.annotation.IdType;
      id-type: input
      #字段策略com.baomidou.mybatisplus.annotation.FieldStrategy
      field-strategy: not_empty
      # 逻辑删除全局值（1表示已删除，Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存,默认为 true
    cache-enabled: false

#    打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ocpmgp:
  common:
    sentry-dsn: ${SENTRY_DSN:https://8822f4ae889b433f9fe72e3904665246@sentry.io/1234888} # mock for test
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET:TEST_SECRET}

swagger:
  basePackage: com.ecdata.cmp.huawei.controller
  title: Cloud Management Product Restful API
  description: 平台-第三方对接平台
  termsOfServiceUrl: http://www.123.com/
  name: ECDATA
  url: http://www.123.com/
  email: admin.com
  version: 1.0

# 租户表维护
tenant:
  defaultId: 10000
  column: tenant_id
  #排除多租户的表（如果涉及的表没有多租户的概念，则在下面进行排除）
  tableFilter:
  - sys_tenant
  - sys_provider
  - sys_manageone
  mapperFilter:
  - com.ecdata.cmp.user.mapper.UserMapper.loadUserByUsername


huawei:
  ManageOne:
    mo_url: https://auth.com
    om_url: https://oc.com
    web_om_url: https://oc.com:31943
    ecs_url: https://ecs.com
    vpc_url: https://vpc.com
    ims_url: https://ims.com
    evs_url: https://evs.com
    bms_url: https://bms.com
  server:
    backendServerIp: 127.0.0.1

  scheduled: false
